objects/Account.object
<CustomObject>
    <fields>
        <fullName>Island_s__c</fullName>
        <description>Organization's main office location</description>
        <inlineHelpText>Organization's main office location</inlineHelpText>
        <label>Island(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Kauai</fullName>
                </value>
                <value>
                    <fullName>Maui</fullName>
                </value>
                <value>
                    <fullName>Oahu</fullName>
                </value>
                <value>
                    <fullName>Lanai</fullName>
                </value>
                <value>
                    <fullName>Molokai</fullName>
                </value>
                <value>
                    <fullName>Multiple Locations</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referred_by_Client_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Read-only because populated from Opportunity (if not Opp, fields from CS Import)</description>
        <inlineHelpText>Read-only because populated from Opportunity (if not Opp, fields from CS Import)</inlineHelpText>
        <label>Referred by Client/Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_BDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to SalesUser (BDM)</description>
        <label>Sales (BDM)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Account_Clients</fullName>
        <active>true</active>
        <description>Accounts that are clients</description>
        <label>Account (Clients)</label>
    </recordTypes>
    <recordTypes>
        <fullName>Account_Prospects</fullName>
        <active>true</active>
        <description>Prospect accounts in the Salespipeline - Does not have a record in Salesforce</description>
        <label>Account (Prospects)</label>
    </recordTypes>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Estimated_Number_of_EEs__c</fullName>
        <description>Estimated number of employees (FT &amp; PT) working for the company</description>
        <inlineHelpText>Estimated number of employees (FT &amp; PT) working for the company</inlineHelpText>
        <label>Estimated # of EEs</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Island_s__c</fullName>
        <description>Island(s) the organization does business in</description>
        <inlineHelpText>Island(s) the organization does business in</inlineHelpText>
        <label>Island(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Kauai</fullName>
                </value>
                <value>
                    <fullName>Lanai</fullName>
                </value>
                <value>
                    <fullName>Maui</fullName>
                </value>
                <value>
                    <fullName>Molokai</fullName>
                </value>
                <value>
                    <fullName>Oahu</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referred_by_Client_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client or Partner that referred the Organization to ProService</description>
        <inlineHelpText>Client or Partner that referred the Organization to ProService</inlineHelpText>
        <label>Referred by Client/Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads_del1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Lead_Assignment_Ids__c.object
<CustomObject>
    <fields>
        <fullName>Island_BDM_Hawaii__c</fullName>
        <description>The alias of the BDM assigned to Hawaii (Big Island)</description>
        <label>Island BDM Hawaii</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Island_BDM_Kauai__c</fullName>
        <description>The alias of the BDM assigned to Kauai</description>
        <label>Island BDM Kauai</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Island_BDM_Lanai__c</fullName>
        <description>The alias of the BDM assigned to Lanai</description>
        <label>Island BDM Lanai</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Island_BDM_Maui__c</fullName>
        <description>The alias of the BDM assigned to Maui</description>
        <label>Island BDM Maui</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Island_BDM_Molokai__c</fullName>
        <description>The alias of the BDM assigned to Molokai</description>
        <label>Island BDM Molokai</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Assignment_Status__c</fullName>
        <description>Status field value on Lead that will be used to trigger the lead assiworkflow.</description>
        <label>Lead Assignment Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major_Account_BDM__c</fullName>
        <description>The alias of the BDM to be assigned to leads when there is a large number of estimated worksite employees</description>
        <label>Major Account BDM</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major_Account_WSE_Count__c</fullName>
        <description>This is the count that determines when the large account BDM should be assigned.</description>
        <label>Major Account WSE Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>User Ids to whom lead would be assigned to.  All islands must be filled in or the lead assignment will fail.</description>
    <label>Lead Assignment UserIDs</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Referred_by_Client_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Referred by Client/Partner</description>
        <inlineHelpText>Referred by Client/Partner</inlineHelpText>
        <label>Referred by Client/Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X1st_Meeting_Occurred__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the first meeting occurred. (If this is not checked then an automation - currently workflow) will update the Account back to being huntable</description>
        <label>1st Meeting Occurred</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LeadTrgHandlerTest.cls
/*
Created by: MB(GTR) - 26-Mar-2018
Summary: Application Trg handler class-Used for Opportunity mapping to application object
*/
@isTest
public class LeadTrgHandlerTest
{
    static string leadAssignmentStatus;
	// test setup data
	@testSetup
    static void setupData()
    {
        leadAssignmentStatus = 'Get Lead Assignment';
        user tUser = [SELECT id, Alias FROM User WHERE Profile.Name = 'System Administrator' AND isActive = true LIMIT 1];
        // create custom setting - leadSettings
        insert new Lead_Assignment_Ids__c(
            Island_BDM_Hawaii__c = tUser.Alias,
            Island_BDM_Kauai__c = tUser.Alias,
            Island_BDM_Lanai__c = tUser.Alias,
            Island_BDM_Maui__c = tUser.Alias,
            Island_BDM_Molokai__c = tUser.Alias,
            Major_Account_BDM__c = tUser.Alias,
            Major_Account_WSE_Count__c = 100,
            Lead_Assignment_Status__c = 'Get Lead Assignment'
        );
        
        // create recordtype map
        Map<string, RecordType> mAccRecTypes = new Map<string, RecordType>(); 
        for(RecordType rt : [SELECT id, Developername, Name FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName in ('Account_Clients', 'Account_Prospects')])
            mAccRecTypes.put(rt.DeveloperName, rt);
        
        // insert 'Account (Clients)' type account
        Account clientAcc = new Account(RecordTypeId=mAccRecTypes.get('Account_Clients').id, Name='test company client partner', Sales_BDM__c=tUser.Id);
        insert clientAcc;
        // create related opportunity
        Opportunity clientOpp = new Opportunity(Accountid=clientAcc.id, Name = 'Test Opp Client', OwnerId = tUser.Id, StageName='1st Meeting Set', CloseDate = Date.today(), X1st_Meeting_Occurred__c = true);
        insert clientOpp;
        // insert 'Account (Prospect)' type account
        Account prospectAcc = new Account(RecordTypeId=mAccRecTypes.get('Account_Prospects').id, Name='test company prospect', Sales_BDM__c=tUser.Id);
        insert prospectAcc;
        // create related opportunity
        Opportunity propspectOpp = new Opportunity(Accountid=prospectAcc.id, Name = 'Test Opp Prospect', OwnerId = tUser.Id, StageName='1st Meeting Set', CloseDate = Date.today(), X1st_Meeting_Occurred__c = true);
        insert propspectOpp;
        // insert leads - Blank Island
        insert new Lead(company='test company blank island', Island_s__c = '', Status = 'New', FirstName = 'FirstName1', LastName = 'LastName1');
        // insert leads - Multiple Islands
        insert new Lead(company='test company blank island', Island_s__c = 'Hawaii;Oahu', Status = 'New', FirstName = 'FirstName1', LastName = 'LastName1');
        // insert leads - Hawaii (Big Island)
        insert new Lead(company='test company Hawaii', Island_s__c = 'Hawaii', Status = 'New', FirstName = 'FirstName1', LastName = 'LastName1');
        // insert lead Kauai
        insert new Lead(company='test company Kauai', Island_s__c = 'Kauai', Status = 'New', FirstName = 'FirstName2', LastName = 'LastName2');
        // insert lead Lanai
        insert new Lead(company='test company Lanai', Island_s__c = 'Lanai', Status = 'New', FirstName = 'FirstName2', LastName = 'LastName2');
        // insert lead Maui
        insert new Lead(company='test company Maui', Island_s__c = 'Maui', Status = 'New', FirstName = 'FirstName2', LastName = 'LastName2');
        // insert lead Molokai
        insert new Lead(company='test company Molokai', Island_s__c = 'Molokai', Status = 'New', FirstName = 'FirstName2', LastName = 'LastName2');
        // Oahu leads below
        // insert lead - Expected employees > 100
        insert new Lead(company='test company emp', Island_s__c = 'Oahu', Estimated_Number_of_EEs__c = 101, Status = 'New', FirstName = 'FirstName3', LastName = 'LastName3');
        // insert lead - client partner - queue assignment
        insert new Lead(company='test company client partner', Island_s__c = 'Oahu', Estimated_Number_of_EEs__c = 99, Status = 'New', FirstName = 'FirstName4', LastName = 'LastName4');
        // insert lead - prospect
        insert new Lead(company='test company prospect', Island_s__c = 'Oahu', Estimated_Number_of_EEs__c = 50, Status = 'New', FirstName = 'FirstName4', LastName = 'LastName4');
        // insert lead - client referral
        insert new Lead(company='test company prospect', Island_s__c = 'Oahu', Estimated_Number_of_EEs__c = 50, Status = 'New', FirstName = 'FirstName4', LastName = 'LastName4', Referred_by_Client_Partner__c = clientAcc.Id);
    }
    
    
    @isTest
    static void testBlankIslands()
    {
        Test.startTest();
        Lead l = [SELECT Company, Status, Island_s__c, OwnerId FROM Lead WHERE Island_s__c = '' LIMIT 1];
        l.Status = 'Get Lead Assignment';
        try {
        	update l;
        }
        catch (Exception e) {
            System.Assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        }
        Test.stopTest();
    }
    @isTest
    static void testMultipleIslands()
    {
        Test.startTest();
        Lead l = [SELECT Company, Status, Island_s__c, OwnerId FROM Lead WHERE Island_s__c = 'Hawaii;Oahu' LIMIT 1];
        l.Status = 'Get Lead Assignment';
        try {
        	update l;
        }
        catch (Exception e) {
            System.Assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        }
        Test.stopTest();
    }
    @isTest
    static void testHawaiiIsland()
    {
        Test.startTest();
        
        Lead l = [SELECT Company, Status, Island_s__c, OwnerId FROM Lead WHERE Island_s__c = 'Hawaii' LIMIT 1];        
        l.Status = 'Get Lead Assignment';
        update l;
        
        Test.stopTest();
    }
    @isTest
    static void testKauaiIsland()
    {
        Test.startTest();
        
        Lead l = [SELECT Company, Status, Island_s__c, OwnerId FROM Lead WHERE Island_s__c = 'Kauai' LIMIT 1];        
        l.Status = 'Get Lead Assignment';
        update l;
        
        Test.stopTest();
    }
    @isTest
    static void testLanaiIsland()
    {
        Test.startTest();
        
        Lead l = [SELECT Company, Status, Island_s__c, OwnerId FROM Lead WHERE Island_s__c = 'Lanai' LIMIT 1];        
        l.Status = 'Get Lead Assignment';
        update l;
        
        Test.stopTest();
    }
    @isTest
    static void testMauiIsland()
    {
        Test.startTest();
        
        Lead l = [SELECT Company, Status, Island_s__c, OwnerId FROM Lead WHERE Island_s__c = 'Maui' LIMIT 1];        
        l.Status = 'Get Lead Assignment';
        update l;
        
        Test.stopTest();
    }
    @isTest
    static void testMolokaiIsland()
    {
        Test.startTest();
        
        Lead l = [SELECT Company, Status, Island_s__c, OwnerId FROM Lead WHERE Island_s__c = 'Molokai' LIMIT 1];        
        l.Status = 'Get Lead Assignment';
        update l;
        
        Test.stopTest();
    }
    @isTest
    static void testMajorAccountAssignment()
    {
        Test.startTest();
        Lead l = [SELECT Company, Status, Island_s__c, OwnerId FROM Lead WHERE Island_s__c = 'Oahu' AND Estimated_Number_of_EEs__c >= 100];
        l.Status = 'Get Lead Assignment';
        update l;
        Test.stopTest();
    }
    @isTest
    static void testUnableToAssign()
    {
        Lead[] leads = new List<Lead>();
        Test.startTest();
        for(Lead l: [SELECT Company, Status, Island_s__c, OwnerId FROM Lead WHERE Island_s__c = 'Oahu' AND Estimated_Number_of_EEs__c < 100]) 
        {
            l.Status = 'Get Lead Assignment';
            leads.add(l);
        }
        try {
        	update leads;
        }
        catch (Exception e) {
            System.Assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        }
        
        Test.stopTest();
    }
        
}