objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Legal_Name__c</fullName>
        <label>Client Legal Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>DBA__c</fullName>
        <label>DBA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Business_Name__c</fullName>
        <label>Legal Business Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Salesforce</fullName>
        <active>true</active>
        <label>Salesforce</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Client_Legal_Name__c</fullName>
        <formula>Account.Client_Legal_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Size__c</fullName>
        <label>Deal Size</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1-5</fullName>
                </value>
                <value>
                    <fullName>6-19</fullName>
                </value>
                <value>
                    <fullName>20-49</fullName>
                </value>
                <value>
                    <fullName>50-99</fullName>
                </value>
                <value>
                    <fullName>100+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ApplicationTrgHandlerTest.cls
/*
Created by: MB(GTR) - 26-Mar-2018
Summary: Application Trg handler class-Used for Opportunity mapping to application object
*/
@isTest
public class ApplicationTrgHandlerTest
{
    @isTest
    static void testApplicationBeforeInsert()
    {
        // create account
        Account acc = new Account (Name = 'Test Account', Client_Legal_Name__c = 'Test Legal Account' );
        insert acc;
        // create opportunity
        Opportunity opp = new Opportunity (Name = 'Test Opportunity', AccountId = acc.Id, StageName = '1st Meeting Set', CloseDate = Date.today(), Deal_Size__c='100+' );
        insert opp;
        
        // insert application record
        Application__c app = new Application__c(Legal_Business_Name__c = 'Test Legal');
        insert app;
        
        // fetch whether or not trigger is active
        ApexTrigger appTrg = [Select Id, Status FROM ApexTrigger WHERE name = 'ApplicationTrg'];
        
        if (appTrg.Status == 'Active') {
            // assert if the application's Opp is updated
            app = [SELECT Legal_Business_Name__c, Opportunity_Name__c, RecordType.Name FROM Application__c WHERE Id =: app.Id];
            System.assertEquals(opp.Id, app.Opportunity_Name__c);
            System.assertEquals('Salesforce', app.RecordType.Name);
        }
    }
	@isTest
    static void testApplicationBeforeUpdate()
    {
        // create account
        Account acc = new Account (Name = 'Test Account', Client_Legal_Name__c = 'Test Legal Account' );
        insert acc;
        // create opportunity
        Opportunity opp = new Opportunity (Name = 'Test Opportunity', AccountId = acc.Id, StageName = '1st Meeting Set', CloseDate = Date.today(), Deal_Size__c='100+' );
        insert opp;
        
        // insert application record
        Application__c app = new Application__c(Legal_Business_Name__c = 'Unmatched account');
        insert app;
        
        app.Legal_Business_Name__c = 'Test Legal';
        update app;
        
        // fetch whether or not trigger is active
        ApexTrigger appTrg = [Select Id, Status FROM ApexTrigger WHERE name = 'ApplicationTrg'];
        
        if (appTrg.Status == 'Active') {
            // assert if the application's Opp is updated
            app = [SELECT Legal_Business_Name__c, Opportunity_Name__c, RecordType.Name FROM Application__c WHERE Id =: app.Id];
            System.assertEquals(opp.Id, app.Opportunity_Name__c);
            System.assertEquals('Salesforce', app.RecordType.Name);
        }
    }
    @isTest
    static void testApplicationBeforeInsertDBA()
    {
        // create account
        Account acc = new Account (Name = 'Test Account', Client_Legal_Name__c = 'Test Legal Account' );
        insert acc;
        // create opportunity
        Opportunity opp = new Opportunity (Name = 'Test Opportunity', AccountId = acc.Id, StageName = '1st Meeting Set', CloseDate = Date.today(), Deal_Size__c='100+' );
        insert opp;
        
        // insert application record
        Application__c app = new Application__c(Legal_Business_Name__c = 'Unmatched legal name', DBA__c = 'Legal Account');
        insert app;
        
        // fetch whether or not trigger is active
        ApexTrigger appTrg = [Select Id, Status FROM ApexTrigger WHERE name = 'ApplicationTrg'];
        
        if (appTrg.Status == 'Active') {
            // assert if the application's Opp is updated
            app = [SELECT Legal_Business_Name__c, Opportunity_Name__c, RecordType.Name FROM Application__c WHERE Id =: app.Id];
            System.assertEquals(opp.Id, app.Opportunity_Name__c);
            System.assertEquals('Salesforce', app.RecordType.Name);
        }
    }
}