objects/Account.object
<CustomObject>
    <fields>
        <fullName>BDM__c</fullName>
        <label>BDM</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Island_s__c</fullName>
        <description>Organization's main office location</description>
        <inlineHelpText>Organization's main office location</inlineHelpText>
        <label>Island(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Kauai</fullName>
                </value>
                <value>
                    <fullName>Maui</fullName>
                </value>
                <value>
                    <fullName>Oahu</fullName>
                </value>
                <value>
                    <fullName>Lanai</fullName>
                </value>
                <value>
                    <fullName>Molokai</fullName>
                </value>
                <value>
                    <fullName>Multiple Locations</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referred_by_Client_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Read-only because populated from Opportunity (if not Opp, fields from CS Import)</description>
        <inlineHelpText>Read-only because populated from Opportunity (if not Opp, fields from CS Import)</inlineHelpText>
        <label>Referred by Client/Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_BDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to SalesUser (BDM)</description>
        <label>Sales (BDM)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Estimated_Number_of_EEs__c</fullName>
        <description>Estimated number of employees (FT &amp; PT) working for the company</description>
        <inlineHelpText>Estimated number of employees (FT &amp; PT) working for the company</inlineHelpText>
        <label>Estimated # of EEs</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Island_s__c</fullName>
        <description>Island(s) the organization does business in</description>
        <inlineHelpText>Island(s) the organization does business in</inlineHelpText>
        <label>Island(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Kauai</fullName>
                </value>
                <value>
                    <fullName>Lanai</fullName>
                </value>
                <value>
                    <fullName>Maui</fullName>
                </value>
                <value>
                    <fullName>Molokai</fullName>
                </value>
                <value>
                    <fullName>Oahu</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referred_by_Client_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client or Partner that referred the Organization to ProService</description>
        <inlineHelpText>Client or Partner that referred the Organization to ProService</inlineHelpText>
        <label>Referred by Client/Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads_del1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Updated_from_code__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating if the record update was made from code/trigger.</description>
        <label>Updated from code</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X1st_Meeting_Date__c</fullName>
        <description>1st Meeting Date</description>
        <inlineHelpText>1st Meeting Date</inlineHelpText>
        <label>1st Meeting Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Lead_Assignment_Ids__c.object
<CustomObject>
    <fields>
        <fullName>Island_BDM_Hawaii__c</fullName>
        <description>The alias of the BDM assigned to Hawaii (Big Island)</description>
        <label>Island BDM Hawaii</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Island_BDM_Kauai__c</fullName>
        <description>The alias of the BDM assigned to Kauai</description>
        <label>Island BDM Kauai</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Island_BDM_Lanai__c</fullName>
        <description>The alias of the BDM assigned to Lanai</description>
        <label>Island BDM Lanai</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Island_BDM_Maui__c</fullName>
        <description>The alias of the BDM assigned to Maui</description>
        <label>Island BDM Maui</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Island_BDM_Molokai__c</fullName>
        <description>The alias of the BDM assigned to Molokai</description>
        <label>Island BDM Molokai</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Assignment_Status__c</fullName>
        <description>Status field value on Lead that will be used to trigger the lead assiworkflow.</description>
        <label>Lead Assignment Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major_Account_BDM__c</fullName>
        <description>The alias of the BDM to be assigned to leads when there is a large number of estimated worksite employees</description>
        <label>Major Account BDM</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major_Account_WSE_Count__c</fullName>
        <description>This is the count that determines when the large account BDM should be assigned.</description>
        <label>Major Account WSE Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>User Ids to whom lead would be assigned to.  All islands must be filled in or the lead assignment will fail.</description>
    <label>Lead Assignment UserIDs</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Referred_by_Client_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Referred by Client/Partner</description>
        <inlineHelpText>Referred by Client/Partner</inlineHelpText>
        <label>Referred by Client/Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X1st_Meeting_Date__c</fullName>
        <description>Date of the 1st meeting. This must be populated in order for an opportunity to be created - even if it already happened</description>
        <label>1st Meeting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X1st_Meeting_Occurred__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the first meeting occurred. (If this is not checked then an automation - currently workflow) will update the Account back to being huntable</description>
        <label>1st Meeting Occurred</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LeadTrgHandler.cls
/*
Created by: MB(GTR) - 19-Mar-2018
Summary: Lead Trg handler class-Used for custom Lead assignments
*/

public class LeadTrgHandler extends TriggerHandler
{ 
    public id oppBDM;
    
    protected override void beforeUpdate() 
    {
        // Lead custom settings
        Lead_Assignment_Ids__c leadSettings = Lead_Assignment_Ids__c.getOrgDefaults();
        // Leads being updated
        List<Lead> leads = (List<Lead>) trigger.new;
        // For referral account matching
        Set<id> referralAccountIds = new Set<id>();
        Map<id, Account> mapReferralAccounts;
        // For company account matching
        Set<string> companyAccounts = new Set<string>();
        Map<string, Account> mapClientAccounts;
        Map<string, Account> mapProspectAccounts;
        
        // Put together list of qualified leads to process
        List<Lead> qualifiedLeads = New List<Lead>();
        for(Lead l: leads)
        {
            system.debug('l.status:' + l.status + ' | leadSettings.Lead_Assignment_Status__c : ' + leadSettings.Lead_Assignment_Status__c);
            
            // check if lead status is Lead_Assignment_Status__c and its old status was not Lead_Assignment_Status__c
            if(l.status == leadSettings.Lead_Assignment_Status__c && ((Lead)trigger.oldMap.get(l.Id)).Status <> leadSettings.Lead_Assignment_Status__c) {
                   qualifiedLeads.add(l);
            }
            if(!String.isBlank(l.Referred_by_Client_Partner__c)) {
                referralAccountIds.add(l.Referred_by_Client_Partner__c);
            }
            if(!String.isBlank(l.Company) ) {
                companyAccounts.add(l.company);
            }
        }
        
        // Process the leads qualified leads
        if(qualifiedLeads.size() > 0)
        {
            if(referralAccountIds.size() > 0 ) 
            {
                mapReferralAccounts = new Map<id, Account>([SELECT name, BDM__c, Sales_BDM__c 
                                                            FROM Account WHERE id IN: referralAccountIds AND RecordType.Name = 'Account (Clients)']);
            }
            if(companyAccounts.size() > 0)
            {
                mapClientAccounts = new Map<string, Account>();
                mapProspectAccounts = new Map<string, Account>();
                for(account acc: [SELECT name, BDM__c, Sales_BDM__c, RecordType.Name,
                                  (SELECT StageName, OwnerId, X1st_Meeting_Occurred__c, X1st_Meeting_Date__c FROM Opportunities WHERE StageName = 'Closed Lost' ) 
                                  FROM Account WHERE Name IN: companyAccounts])
                {
                    if(acc.RecordType.Name == 'Account (Clients)') mapClientAccounts.put(acc.Name, acc);
                    else if (acc.RecordType.Name == 'Account (Prospects)') mapProspectAccounts.put(acc.Name, acc);
                }
            }
            for(Lead ql: qualifiedLeads)
            {
                System.debug('mapProspectAccounts: ' + mapProspectAccounts.containsKey(ql.Company) ); 
                // approval will be fired only when the following field is TRUE
                ql.Updated_from_code__c = true;
                
                // Check that at least 1 island has been selected.  If not, return early with an error.
                if (String.isBlank(ql.Island_s__c)) {
                    ql.Island_s__c.addError('Please choose 1 or more to ensure proper geographic assignment');
                    return;
                }
                
                system.debug('islands:' + ql.Island_s__c);
                List<String> islands = ql.Island_s__c.split(';');
                
                // 0. Junk check to make moving conditionals below easier
                if (false) {
                    return;
                }
                // 0.1 If multiple islands are selected defer back to the user to manually assign
                else if (islands.size() > 1) {
                    ql.Island_s__c.addError('Multiple islands are selected, please manually assign this lead based on the rotor distribution rules');
                    return;
                }
                // 1. Island (territory) rules are always processed first
                else if (islands.contains('Hawaii'))
                {
                    // Assign to BDM defined for Hawaii (Big Island)
                    List<User> newOwnerID = [SELECT Id FROM User WHERE Alias = :leadSettings.Island_BDM_Hawaii__c LIMIT 1];
                    
                    // If no BDM is currently assigned to this island in the settings error and return
                    if (newOwnerID.size() == 0) {
                        ql.addError('No BDM assigned to Hawaii (Big Island), please manually assign');
                        return;
                    }
                    
                    ql.OwnerId = newOwnerID[0].Id;
                }
                else if (islands.contains('Kauai'))
                {
                    // Assign to BDM defined for Kauai
                    List<User> newOwnerID = [SELECT Id FROM User WHERE Alias = :leadSettings.Island_BDM_Kauai__c LIMIT 1];
                    
                    // If no BDM is currently assigned to this island in the settings error and return
                    if (newOwnerID.size() == 0) {
                        ql.addError('No BDM assigned to Kauai, please manually assign');
                        return;
                    }
                    
                    ql.OwnerId = newOwnerID[0].Id;
                }
                else if (islands.contains('Lanai'))
                {
                    // Assign to BDM defined for Lanai
                    List<User> newOwnerID = [SELECT Id FROM User WHERE Alias = :leadSettings.Island_BDM_Lanai__c LIMIT 1];
                    
                    // If no BDM is currently assigned to this island in the settings error and return
                    if (newOwnerID.size() == 0) {
                        ql.addError('No BDM assigned to Lanai, please manually assign');
                        return;
                    }
                    
                    ql.OwnerId = newOwnerID[0].Id;
                }
                else if (islands.contains('Maui'))
                {
                    // Assign to BDM defined for Maui
                    List<User> newOwnerID = [SELECT Id FROM User WHERE Alias = :leadSettings.Island_BDM_Maui__c LIMIT 1];
                    
                    // If no BDM is currently assigned to this island in the settings error and return
                    if (newOwnerID.size() == 0) {
                        ql.addError('No BDM assigned to Maui, please manually assign');
                        return;
                    }
                    
                    ql.OwnerId = newOwnerID[0].Id;
                }
                else if (islands.contains('Molokai'))
                {
                    // Assign to BDM defined for Molokai
                    List<User> newOwnerID = [SELECT Id FROM User WHERE Alias = :leadSettings.Island_BDM_Molokai__c LIMIT 1];
                    
                    // If no BDM is currently assigned to this island in the settings error and return
                    if (newOwnerID.size() == 0) {
                        ql.addError('No BDM assigned to Molokai, please manually assign');
                        return;
                    }
                    
                    ql.OwnerId = newOwnerID[0].Id;
                }
                // Should be Oahu leads only beyond this point
                // 2. By estimated worksite employee count - If 100 or more then assign to major account BDM (Major Account Manager)
                else if(ql.Estimated_Number_of_EEs__c >= leadSettings.Major_Account_WSE_Count__c) 
                {
                    List<User> newOwnerID = [SELECT Id FROM User WHERE Alias = :leadSettings.Major_Account_BDM__c LIMIT 1];
                    
                    // If no BDM is currently assigned to large accounts in the settings error and return
                    if (newOwnerID.size() == 0) {
                        ql.addError('No BDM assigned to major accounts, please manually assign');
                        return;
                    }
                    ql.OwnerId = newOwnerID[0].Id;
                }
                //  3. relationship: 
                else if (!String.isBlank(ql.Referred_by_Client_Partner__c) && mapReferralAccounts <> null)
                {
                    System.debug('Inside cond 3a');
                    // 3a. Look at the Referred Account Field on Lead > Look at the BDM associated with the Account - Assign Lead to that BDM 
                    ql.OwnerId = mapReferralAccounts.get(ql.Referred_by_Client_Partner__c).Sales_BDM__c;
                }
                else if (mapClientAccounts <> null && mapClientAccounts.containsKey(ql.Company) && mapClientAccounts.get(ql.Company).Opportunities <> null)
                {
                    System.debug('Inside cond 3b' + JSON.serialize(mapClientAccounts) );
                    // 3b. Will search for existing Account (client) by exact name on Company field on Lead - If found and matches - will look at BDM lookup field on Account  
                    if(String.isBlank(mapClientAccounts.get(ql.Company).Sales_BDM__c)) ql.addError('Lead has a matching account with Opportunity but Opp BDM is not set.');
                    else ql.OwnerId = mapClientAccounts.get(ql.Company).Sales_BDM__c;
                }
                
                // 4.   Step 1: Find a matching Account - Prospect
                else if (mapProspectAccounts.containsKey(ql.Company) && checkAccountsWithOpp90DaysOrLess(mapProspectAccounts, ql.Company))
                {
                    System.debug('Inside cond 4b > ' + oppBDM);
                    ql.OwnerId = oppBDM;
                }
                else
                {
                    System.debug('Unable to get lead assignment');
                    // assign round-robin
                    ql.Updated_from_code__c = false;
                    // assign this lead to an open queue
                    // ql.OwnerId = leadSettings.Open_Queue_ID__c;
                    ql.addError('Unable to get lead assignment, please manually assign this lead based on rotor distribution rules');
                }
                
            }
        }
    }
    
    private boolean checkAccountsWithOpp90DaysOrLess(Map<string, Account> accWithOpps, String leadCompany)
    {
        // 4b.  Step 1: Find a matching Account - Prospect
        //      Step 2: find a Closed Lost Opportunity - If only one, end of story, assign BDM to that lead 
        //      Step 3: If more than one closed lost opportunity, find the 1st meeting date is within 90 days of the lead creation date assign this lead to the BDM of that opportunity/ Most recent date will be selected if two 1st meetings date within 90 days.  
        
        // this method returns true if the 1stMeeting create within 90 days and sets the lead owner to Opp BDM
        boolean condOppWith1stMeeting90Below = false;
        system.debug('4. checkAccountsWithOpp90Below:' + accWithOpps + ' - ' + leadCompany + '-condOppWith1stMeeting90Below:' + condOppWith1stMeeting90Below);
        // this method checks if the lead company exists in 
        if (accWithOpps.containsKey(leadCompany) && accWithOpps.get(leadCompany).Opportunities.size() > 0)
        {
            // check related Opps
            for(Opportunity opp: accWithOpps.get(leadCompany).Opportunities) 
            {
                // assign Lead to the Opp Owner (BDM)
                oppBDM = opp.OwnerId;
                system.debug('opp.X1st_Meeting_Occurred__c' + opp.X1st_Meeting_Occurred__c);
                if(opp.X1st_Meeting_Occurred__c == true && (opp.X1st_Meeting_Date__c.daysBetween(System.today()) <= 90)) 
                {
                    system.debug('X1st_Meeting_Occurred__c' + opp.X1st_Meeting_Occurred__c);
                    // 
                    condOppWith1stMeeting90Below = true;
                    oppBDM = opp.OwnerId;
                    return condOppWith1stMeeting90Below;
                }
                
            }
        }
        return condOppWith1stMeeting90Below;
        
    }
    
}